---
name: Typing

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.13"

permissions:
  contents: read

jobs:
  ty:
    name: ty
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        # yamllint disable-line rule:line-length
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: 🏗 Set up uv
        # yamllint disable-line rule:line-length
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
      - name: 🏗 Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: 🏗 Install dependencies
        run: uv sync --dev
      - name: 🚀 Run ty
        run: uv run ty check src tests
